version: '3'
services:
 # Nginx Service
 nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
 # PHP Service
 php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    depends_on:
      - database
 database:
    image: postgres:latest # Usa a imagem mais recente do PostgreSQL
    environment:
      POSTGRES_DB: laravel # Nome do banco de dados
      POSTGRES_USER: laravel # Usuário do banco de dados
      POSTGRES_PASSWORD: laravel # Senha do usuário do banco de dados
    volumes:
      - db:/var/lib/postgresql/data # Define um volume para persistência dos dados do PostgreSQL

  # Redis Service
 redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expõe a porta padrão do Redis
    volumes:
      - redis_data:/data # Define um volume para persistência dos dados do Redis

# Declaração de volumes
volumes:
  db:
  redis_data:
